### ISSUE TITLE
Incorrect instructions when installing via brew on linux

### ISSUE THREAD

**Issue by gmile** [nuspell/homebrew-nuspell#2]
When installing nuspell via homebrew on Linux, e.g.:

```
brew install nuspell/homebrew-nuspell/nuspell
```

The following instructions are the output:

```
Dictionary files (*.aff and *.dic) should be placed in
~/Library/Spelling/ or /Library/Spelling/.  Homebrew itself
provides no dictionaries for Nuspell, but you can download
compatible Hunspell dictionaries from other sources, such as
https://wiki.documentfoundation.org/Language_support_of_LibreOffice
```

When installing on linux via homebrew, this block of text should probably output Linux-specific directories, one of paths mention here maybe?

https://github.com/nuspell/nuspell/commit/bb1758381d393b931ea566b22ede23636f0ab067#diff-8212e76f47f3a8b9642435d8e254595cca4d4175c92d08793c0b99fe4caa9f06R29-R33

**Comment by dimztimz** [comment]
Than you for noticing this. Fell free to write better message and send it as PR, or just write it here.

You might be also interested to put this package into upstream Homebrew.

**Comment by dimztimz** [comment]
Ping @gmile.
